class Hipster < ActiveRecord::Base
  def self.output(num=1)
    [
    "Aesthetic jean shorts selvage disrupt. Cold-pressed meditation craft beer American Apparel wayfarers lomo. IPhone master cleanse cray banjo, tote bag cornhole Pinterest fashion axe locavore. PBR ennui Banksy mustache whatever Carles PBR&B vinyl. Sustainable kale chips tattooed Echo Park +1, shabby chic taxidermy occupy tousled tilde kitsch church-key cred. Chambray Austin wolf taxidermy food truck, butcher DIY semiotics next level readymade forage deep v. Dreamcatcher fixie whatever artisan.",
    "Tilde seitan kogi Pitchfork trust fund jean shorts. Hashtag lomo put a bird on it next level locavore flannel. Squid next level Intelligentsia, you probably haven't heard of them tattooed distillery heirloom meh pour-over leggings trust fund Vice. Before they sold out stumptown Pinterest kale chips, DIY yr beard health goth PBR&B distillery. Godard actually flannel yr, tousled Marfa Carles church-key Neutra. Vinyl small batch post-ironic, typewriter sustainable beard cardigan American Apparel food truck iPhone direct trade tote bag keffiyeh. Brunch sriracha heirloom, Williamsburg swag chambray small batch.",
    "Put a bird on it retro leggings bespoke, mumblecore polaroid readymade squid. Plaid kale chips Wes Anderson twee pour-over, DIY readymade XOXO migas vinyl ethical chia photo booth umami wayfarers. Cray forage kale chips master cleanse, cornhole Echo Park XOXO four loko umami cliche swag Odd Future trust fund mustache pickled. Letterpress ethical seitan tofu hella. Aesthetic authentic roof party Carles locavore messenger bag. Messenger bag twee put a bird on it wolf, master cleanse quinoa normcore hella Helvetica meh banjo. Typewriter Kickstarter sartorial, locavore cardigan fingerstache listicle stumptown yr crucifix Pitchfork 8-bit.",
    "Wayfarers freegan chillwave Vice. Ethical chia tote bag fashion axe hashtag, McSweeney's stumptown four dollar toast Thundercats gentrify cliche occupy pickled tofu. Brooklyn 3 wolf moon tousled direct trade Pitchfork pug small batch. Before they sold out forage leggings keffiyeh sartorial Shoreditch Austin you probably haven't heard of them Truffaut stumptown swag. Dreamcatcher fap mustache direct trade deep v. Kale chips master cleanse High Life cliche, Tumblr lomo tattooed readymade normcore paleo narwhal heirloom. American Apparel crucifix try-hard shabby chic Blue Bottle wayfarers normcore keffiyeh, Carles single-origin coffee Helvetica DIY cold-pressed cray."
    ]
  end
end
