class Standard < ActiveRecord::Base
  def self.output(num = 1)
    [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur a feugiat metus, ut venenatis diam. Fusce ut cursus erat. Nulla eget bibendum erat. Aenean pulvinar urna risus, nec rutrum est feugiat et. Praesent vitae imperdiet nisl, in tristique urna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer tristique tincidunt nibh, id aliquet leo semper sit amet. Nulla venenatis ante efficitur sagittis euismod. Nunc non congue sem. In posuere ligula in gravida imperdiet. Mauris pharetra iaculis arcu non tincidunt. Sed consequat sodales augue vel molestie. Suspendisse id massa mattis, laoreet nulla vel, placerat enim.",
      "Vestibulum non rhoncus sapien, ut porta mi. Suspendisse molestie viverra justo sed eleifend. Suspendisse mollis volutpat tellus ut maximus. Curabitur ut quam aliquet, cursus sapien vitae, tincidunt sem. Fusce in ligula quis neque efficitur porta quis ac urna. Praesent egestas tristique ante, vitae scelerisque turpis mattis quis. Pellentesque vitae tristique nulla. In sit amet vulputate arcu. Morbi eget justo pharetra, suscipit lacus eu, tempor lorem. Proin malesuada est non diam consequat, quis aliquam enim tempus. Praesent at pellentesque nulla, accumsan rutrum nisi. Curabitur vel nisi venenatis, venenatis purus pretium, porta ex.",
      "Phasellus molestie neque vel ex finibus, et vehicula lacus sollicitudin. Aliquam et tincidunt sapien. Proin gravida urna quis ante pulvinar, non iaculis neque blandit. Proin sodales tristique consequat. Fusce sapien dui, elementum et sodales volutpat, vehicula ut tortor. Nulla eleifend a sem ut consequat. Fusce sit amet volutpat diam, ac tristique sem. Pellentesque blandit mollis placerat. Donec ornare dui a urna mollis, at egestas est bibendum. Etiam bibendum tortor et urna vulputate, id auctor lorem placerat. Morbi vitae varius ipsum. Pellentesque nec ex scelerisque, porta tortor ut, varius sem. Nam at ligula turpis.",
      "Vivamus maximus euismod est, aliquam euismod nisi efficitur quis. Suspendisse cursus, metus a pretium vulputate, lorem ex convallis nibh, in dignissim augue metus vel arcu. Integer aliquam enim felis, nec porta quam cursus ut. Phasellus magna mauris, venenatis ac imperdiet sit amet, interdum at tellus. Sed at convallis leo. Aliquam erat volutpat. Duis hendrerit volutpat elementum. Cras nibh dolor, tincidunt eu diam quis, malesuada condimentum nulla. Nam in convallis tortor. Duis ultrices ornare est, vel sodales est suscipit vel. Ut eget arcu et tortor volutpat tempor. Duis vehicula, orci dictum venenatis lacinia, ante orci facilisis dolor, id facilisis mauris odio id sem. Fusce pellentesque hendrerit tortor, vitae porta ligula vehicula et. Vivamus tempus tempus porta. Vivamus sapien erat, venenatis eu elit non, dictum tincidunt sapien."
    ]
  end
end
